config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}

  resources :products do
   resources :comments
  end
  resources :users

  resources :orders, only: [:index, :show, :create, :destroy]
  post 'payments/create'

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'

  get 'static_pages/landing_page'

  post 'static_pages/thank_you'

   root 'static_pages#landing_page'

  resources :orders, only: [:index, :show, :create, :destroy]

  
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :comments
  has_many :orders
  validates :name, presence: true

  def average_rating
    comments.average(:rating).to_f  
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :destroy, :update]
  #load_and_authorize_resource
  respond_to :json, :html

  # GET /products
  # GET /products.json

 # def index
  #  @products =Product.all
   # search_term = params[:q]
 # end
 
  def index   
    if params[:q]
      search_term = params[:q]
      @products = Product.where("name LIKE ?", "%#{search_term}%") 
    else
      @products = Product.all
    end
    
    respond_with @products
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @comments = @product.comments.order("created_at DESC").paginate(:page => params[:page], :per_page => 2)
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_product
      @product = Product.find(params[:id])
      Rails.logger.debug "I have just loaded the product with name : #{@product.name}"
    end  
    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :colour, :price)
    end
    
end

app/helpers/products_helper.rb
module ProductsHelper
  def cache_key_for_products
    count     = Product.count
    max_updated_at = Product.maximum(:updated_at).try(:to_s, :number)
    "products/all-#{count}-#{max_updated_at}"
  end
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
     <%= f.label :colour %><br>
     <p><%= f.text_field :colour %><p/>
  </div>
  <div class="field">
     <%= f.label :price %><br>
     <p><%= f.text_field :price %><p/>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  
<% end %>

app/views/products/_new_comment.html.erb
<% if signed_in? %>

  <h4>Add a review:</h4>
  <%= form_for([@product, @product.comments.build], remote: true) do |f| %>
    <p>
      <%= f.label :body, "Comments" %><br>
      <%= f.text_area :body %>
    </p>
    <p>
    <div class="rating"></div>
     <%# f.label :rating  %>
     <br>
     <%# f.text_field :rating %>
    </p>
    <p>
      <%= f.submit "Submit" %>
    </p>
     
  <% end %>
<% end %> 

app/views/products/_product.html.erb

<% logger.debug "Product:#{@product.name}"%>

    <% cache product do %>
      <p><%= product.name %></p>
      <p><%= product.description %></p>
      <p><%= product.colour %></p>
      <p><%= product.image_url %></p>
      <p><%= link_to 'Show', product %>
        <%= link_to 'Edit', edit_product_path(product) %>
        <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></p>
    <% end %>

    <%= render @products %>
 

app/views/products/edit.html.erb
<div class="container-fluid">
  <h1>Editing product</h1>

  <%= render 'form' %>

  <%= link_to 'Show', @product %> |
  <%= link_to 'Back', products_path %>
</div>

app/views/products/index.html.erb
<div class="container-fluid">
  
  <% cache(cache_key_for_products) do %>
      
      <div class="row">
        <h1>All Our products</h1>
      </div>

          <div class="row">    
            <div class="col-md-3">
              <% @products.each do |product| %>     
                <p><%= product.name %></p>
                <p><%= product.description %></p>
                <p><%= product.colour %></p>
                <p><%= product.image_url %></p>
                <p><%= link_to 'Show', product %>
                  <%= link_to 'Edit', edit_product_path(product) %>
                  <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></p>            
              <% end %> 
            </div>  
          </div> 

  <% end %>
  
</div>

app/views/products/new.html.erb
<div class="container-fluid">
  <h1>New product</h1>

  <%= render 'form' %>

  <%= link_to 'Back', products_path %>
</div>

app/views/products/show.html.erb
<div class="container-fluid view" >

  <p id="notice"><%= notice %></p>
  
<% cache @product do %>

  <div class="col-md-8">
     <%= image_tag(@product.image_url, width: "350", class: "img-zoom", 'data-zoom-image' => image_url(@product.image_url)) %>
  </div>  

    <div class="col-md-4">
          <p>
            <h2><%= @product.name %></h2>
          </p>

          <p>          
            <%= @product.description %>
          </p>

          <p>
             <strong>Colour:</strong>
             <%= @product.colour %>
          </p>
          <p>
             <strong>Price :</strong>
             <%= @product.price  %>
          </p>

          
          <p>
            Average Rating: <div class="rated" data-score="<%= @product.average_rating %>"></div>
          </p>
       
          <%= link_to 'Edit', edit_product_path(@product) %> 
          <%= link_to 'Back', products_path %>

    </div>

        <%= render partial: "new_comment" %>
      
       

    <div class="product-reviews">
        <% @comments.each do |comment| %>

          <%= form_tag "/payments/create" do %>
            <%= hidden_field_tag :product_id, @product.id %>
            <%= render partial: "shared/stripe_checkout_button", locals: {product: @product} %>
           <% end %>
            
          <div class="row">
            <hr>             
              <p>
                <%= comment.user.first_name %> <small><em><%= "#{time_ago_in_words(comment.created_at)} ago" %></em></small>
                <% if signed_in? && current_user.admin? %>
                <%= link_to ('<i class="fa fa-trash"></i>').html_safe, product_comment_path(@product, comment), method: :delete, data: { confirm: 'Are you sure?' } %>
                <% end %>
              </p>
              <div class="rated" data-score="<%= comment.rating %>"></div>
              <p><%= comment.body %></p>
          </div>
        <% end %>
<% end %>     
       <%= will_paginate @comments, renderer: BootstrapPagination::Rails %>
    </div>
</div>