config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}

  resources :products do
   resources :comments
  end
  resources :users

  resources :orders, only: [:index, :show, :create, :destroy]
  post 'payments/create'

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'

  get 'static_pages/landing_page'

  post 'static_pages/thank_you'

   root 'static_pages#landing_page'

  resources :orders, only: [:index, :show, :create, :destroy]

  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html >
<head>
  <title>thato_eshop</title>

  <!--<link href=../stylesheets/bike.css.css rel="stylesheet"> -->
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
</head>
<body class='<%= "#{controller_name} #{action_name}"%>'>

  <% if notice %>
  <p id="notice" class="alert alert-info"><%= notice %></p>
  <% end %>

  <% if notice %>
  <p id="alert" class="alert alert-info"><%= alert %></p>
  <% end %>

  <%= flash[:notice] %>
  
<nav class="navbar navbar-inverse navbar-fixed-top">   <!--  Navigation Bar -->
    
    <!-- Code for search form -->
    <div class="form">
     <%= form_tag("/products", method: "get") do %>
        <%= label_tag(:q, "Search Bikes:") %>
        <%= text_field_tag(:q) %>
        <%= submit_tag("Search Now") %>
     <% end %>
    </div>
      <!-- End of Code for search form -->

      <div class="container" >
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#"><mark>Thato_Eshop</mark></a>
        </div>
        <div  class="collapse navbar-collapse" >
          <ul class="nav navbar-nav" >

            <li class="<%= action_name=='landing_page' ? 'active' : nil %>">
            <%= link_to "Home", static_pages_landing_page_path %></li>

           <!-- <li class="<%= action_name=='index' ? 'active' : nil %>"> -->
             <!-- <%= link_to "Home", static_pages_index_path %></li> -->
             <!--  <a href="static_pages_index_path">Home</a></li>-->
             
            <li class="<%= action_name=='about' ? 'active' : nil %>">
              <%= link_to "About",static_pages_about_path %></li>
             <!--  <a href="static_pages_about_path">About</a></li>-->
             
            <li class="<%= action_name=='contact' ? 'active' : nil %>">
              <%= link_to "Contact",static_pages_contact_path %></li>
              <!-- <a href="static_pages_contact_path">Contact</a></li>-->

            <li class="<%= action_name=='index' ? 'active' : nil %>">
              <%= link_to "Our_Products",products_path %></li>
            
          </ul>
          
          <ul class="nav pull-right">
            <li>
                <% if user_signed_in? %>
                  <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
                <% else %>
                   <%= link_to('Login', new_user_session_path) %>
                <% end %>
            </li>
          </ul>

        </div><!--/.nav-collapse -->
      </div>
</nav> <!-- End of navigation bar -->


 


     <div class="header">
      <h1><em><u>Welcome to Bike SA</u></em></h1><br>
      
      <h2>Your source for used  bikes in Johannesburg</h2>
     </div>  


   <%= yield %>

  <footer>
   <nav class="col-md-3" >
     
      <nav class="twitter" >
        <!--<%= Time.now %>-->
        <a href="https://twitter.com/thatomkt" class="twitter-follow-button" data-show-count="false" data-size="large" data-dnt="true">Follow @thatomkt</a>

        <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
        
      </nav> 
   </nav>
       <nav class="col-md-3">
           <%= Time.now %>           
       </nav>

   <nav class="col-md-6">
     &copy 2015 mktDevelopers
   </nav>
  			
  </footer>

</body>
</html>